### ISSUE TITLE
Units that aren't testable or just powers on.

### ISSUE THREAD

**Issue by RogueBard** [hschreck/Aura#6]
We are needing to input additional information for products that aren't able to be tested or just power on only.  When creating an ad we have to describe exactly what's wrong with the information. If you guys can think of a way to include this with the "Powers on, tested, etc..." sticker that gets attached to products that would be great. Of course if you need any additional information or help I'm here.

Thanks!

**Comment by sydneybrokeit** [comment]
Yeah, we can include a field for it

**Comment by 128keaton** [comment]
Templating to the rescue!
